// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package wire

import (
	"database/sql"
	"github.com/echizenn/techtrain_CA_Tech_Dojo_Server_Side/api"
	"github.com/echizenn/techtrain_CA_Tech_Dojo_Server_Side/application"
	"github.com/echizenn/techtrain_CA_Tech_Dojo_Server_Side/domain/service"
	"github.com/echizenn/techtrain_CA_Tech_Dojo_Server_Side/infrastructure"
)

// Injectors from wire.go:

func InitGameAPI(db *sql.DB) api.GameAPI {
	iUserRepository := infrastructure.NewUserRepository(db)
	userIDService := service.NewUserIDService(iUserRepository)
	userTokenService := service.NewUserTokenService(iUserRepository)
	userApplicationService := application.NewUserApplicationService(iUserRepository, userIDService, userTokenService)
	iCharacterRepository := infrastructure.NewCharacterRepository(db)
	iUsersCharactersRepository := infrastructure.NewUsersCharactersRepository(iCharacterRepository, db)
	gachaService := service.NewGachaService(iCharacterRepository)
	gachaApplicationService := application.NewGachaApplicationService(iUserRepository, iUsersCharactersRepository, gachaService)
	usersCharactersApplicationService := application.NewUsersCharactersApplicationService(iUserRepository, iUsersCharactersRepository)
	gameAPI := api.NewGameAPI(userApplicationService, gachaApplicationService, usersCharactersApplicationService)
	return gameAPI
}
